name: Go

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:

    strategy:
      matrix:
        go: [ 'stable', 'oldstable', '1.19' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Lint Go code
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.55.2"

      - name: Test
        run: go test -race -cover ./...
